from typing import Any, Awaitable

class AsyncWebClient:
    async def views_open(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    async def files_upload_v2(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    async def chat_postMessage(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    async def chat_postEphemeral(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    async def conversations_join(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    async def reactions_add(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    async def admin_emoji_add(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
