from typing import Any, Optional
from .async_slack_response import AsyncSlackResponse

class AsyncWebClient:
    def __init__(self, *, token: Optional[str] = ..., **kwargs: Any) -> None: ...
    async def views_open(self, *args: Any, **kwargs: Any) -> AsyncSlackResponse: ...
    async def files_upload_v2(
        self, *args: Any, **kwargs: Any
    ) -> AsyncSlackResponse: ...
    async def chat_postMessage(
        self, *args: Any, **kwargs: Any
    ) -> AsyncSlackResponse: ...
    async def chat_postEphemeral(
        self, *args: Any, **kwargs: Any
    ) -> AsyncSlackResponse: ...
    async def conversations_join(
        self, *args: Any, **kwargs: Any
    ) -> AsyncSlackResponse: ...
    async def reactions_add(self, *args: Any, **kwargs: Any) -> AsyncSlackResponse: ...
    async def admin_emoji_add(
        self, *args: Any, **kwargs: Any
    ) -> AsyncSlackResponse: ...
    # Additional commonly used methods for future use
    async def users_info(self, *args: Any, **kwargs: Any) -> AsyncSlackResponse: ...
    async def conversations_info(
        self, *args: Any, **kwargs: Any
    ) -> AsyncSlackResponse: ...
    async def views_update(self, *args: Any, **kwargs: Any) -> AsyncSlackResponse: ...
    async def chat_update(self, *args: Any, **kwargs: Any) -> AsyncSlackResponse: ...
    async def files_delete(self, *args: Any, **kwargs: Any) -> AsyncSlackResponse: ...
