from typing import Any, Callable

class FastAPI:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, path: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def post(self, path: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class Request:
    headers: dict[str, str]
    async def body(self) -> bytes: ...
