name: Deploy Emoji Smith

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Stage 1: Code Quality
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        uv sync

    - name: Run pre-commit hooks
      run: |
        uv run pre-commit run --all-files

    - name: Code formatting check
      run: |
        uv run black --check src/ tests/

    - name: Lint with flake8
      run: |
        uv run flake8 src/ tests/

    - name: Type checking with mypy
      run: |
        uv run mypy src/

  # Stage 2: Security
  security:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        uv sync

    - name: Security analysis with bandit
      run: |
        uv run bandit -r src/

  # Stage 3: Testing
  testing:
    runs-on: ubuntu-latest
    needs: security
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        uv sync

    - name: Run tests with coverage
      run: |
        uv run pytest --cov=src --cov-fail-under=80 --cov-report=xml tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  # Stage 4: Build (Docker image and ECR push)
  build:
    runs-on: ubuntu-latest
    needs: testing
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    outputs:
      image-uri: ${{ steps.build-image.outputs.image }}
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: emoji-smith
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  # Stage 5: Deploy (CDK deployment to AWS Lambda)
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Node.js for CDK
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Install CDK dependencies
      working-directory: ./infra
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: CDK Deploy with new image
      working-directory: ./infra
      env:
        IMAGE_URI: ${{ needs.build.outputs.image-uri }}
      run: |
        source .venv/bin/activate
        cdk deploy --require-approval never --context imageUri=$IMAGE_URI