name: Deploy Emoji Smith

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync

    - name: Code formatting check
      run: |
        uv run black --check src/ tests/

    - name: Lint with flake8
      run: |
        uv run flake8 src/ tests/

    - name: Type checking with mypy
      run: |
        uv run mypy src/

    - name: Security analysis with bandit
      run: |
        uv run bandit -r src/

    - name: Run tests with coverage
      run: |
        uv run pytest --cov=src --cov-fail-under=80 tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install Node.js for CDK
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Install CDK dependencies
      working-directory: ./infra
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: CDK Deploy
      working-directory: ./infra
      run: |
        source .venv/bin/activate
        cdk deploy --require-approval never